### ISSUE TITLE
Is there a reason why "react":"^16.8.1" is set in peerDependencies?

### ISSUE THREAD

**Issue by matsuda-argano** [saadqbal/react-native-notification-sounds#29]
Thanks for the great library!

I am using React version 17.0.2 in my project, but I get an error during installation because "react":"^16.8.1" is set in peerDependencies.

Is it necessary to specify peerDependencies?

**Comment by saadqbal** [comment]
Resolved in the latest release

**Comment by matsuda-argano** [comment]
@saadqbal 

Thanks for the correction.

However, it is still not available in React 18.

Is there any reason for this?

**Comment by iamifechi** [comment]
@saadqbal would adding the asterisks wildcard for the peer_dependencies solve this? I have to review other RN package peer dependencies and they all used '*', I don't know if this would cause any breaking change. What do you think?
